services:
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /postgres/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/postgres/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres-data: